export default [
    {
        name: "Muscle Up",
        showActiveTime: false,
        showWeight: false,
        variations: ["standard", "kipping"],
    },
    {
        name: "Pull Up",
        showActiveTime: false,
        showWeight: false,
        variations: ["standard", "explosive"],
    },
    {
        name: "Chin Up",
        showActiveTime: false,
        showWeight: false,
        variations: [],
    },
    {
        name: "Front Lever",
        showActiveTime: true,
        showWeight: false,
        variations: ["tucked", "advanced tuck", "one leg", "straddle", "full"],
    },
    {
        name: "Back Lever",
        showActiveTime: true,
        showWeight: false,
        variations: ["tucked", "advanced tuck", "one leg", "straddle", "full"],
    },
    {
        name: "German Hang",
        showActiveTime: true,
        showWeight: false,
        variations: [],
    },
    {
        name: "Push Up",
        showActiveTime: false,
        showWeight: false,
        variations: ["standard", "archer", "diamond", "sphinx", "one arm"],
    },
    {
        name: "Reverse Push Up",
        showActiveTime: false,
        showWeight: false,
        variations: [],
    },
    {
        name: "Dips",
        showActiveTime: false,
        showWeight: false,
        variations: ["parallel bars", "horizontal bar"],
    },
    {
        name: "Hanging Leg Raise",
        showActiveTime: false,
        showWeight: false,
        variations: [],
    },
    {
        name: "Crunch",
        showActiveTime: false,
        showWeight: false,
        variations: [],
    },
    {
        name: "Sit Up",
        showActiveTime: false,
        showWeight: false,
        variations: [],
    },
    {
        name: "Hollow Crunch",
        showActiveTime: false,
        showWeight: false,
        variations: [],
    },
    {
        name: "Dragonflag",
        showActiveTime: false,
        showWeight: false,
        variations: ["standard", "negative", "hold"],
    },
    {
        name: "Handstand",
        showActiveTime: true,
        showWeight: false,
        variations: ["floor", "wall"],
    },
    {
        name: "Frogstand",
        showActiveTime: true,
        showWeight: false,
        variations: ["standard", "one knee", "one knee - straight leg"],
    },
    {
        name: "Planche",
        showActiveTime: true,
        showWeight: false,
        variations: ["tuck", "advanced tuck", "one leg", "staddle", "full"],
    },
    {
        name: "Wall sit",
        showActiveTime: true,
        showWeight: false,
        variations: ["standard", "one leg"],
    },
    {
        name: "L sit",
        showActiveTime: true,
        showWeight: false,
        variations: ["floor", "rings", "hanging", "parallel bars"],
    },
    {
        name: "V sit",
        showActiveTime: true,
        showWeight: false,
        variations: ["floor", "rings", "hanging", "parallel bars"],
    },
]
